name: Sync kernel_oneplus_sm8250 repository

on:
  schedule:
    - cron: '0 0 * * *' # 每小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the target repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }} # 用于访问目标仓库的个人访问令牌，需要在仓库设置中的Secrets中添加
        repository: PianCat/android_KernelSU_kernel_oneplus_sm8250
        path: target_repo
        fetch-depth: 0 # 获取所有分支

    - name: Fetch all branches from source repository
      run: |
        cd target_repo
        git remote add source_repo https://github.com/HELLBOY017/kernel_oneplus_sm8250.git
        git fetch source_repo
        git remote set-branches --add source_repo '*'
        git fetch --all
    - name: Sync all branches or oos branch
      run: |
        cd target_repo
        BRANCHES=$(git branch -r | grep 'source_repo/' | grep -v 'HEAD' | awk '{print $1}' | sed 's/source_repo\///')
        if [ -z "$BRANCHES" ]; then
          echo "No branches found. Syncing oos branch."
          BRANCHES="oos"
        fi
        for branch in $BRANCHES; do
          echo "Syncing branch: $branch"
          git checkout --track source_repo/$branch || git checkout $branch # 使用完整的源仓库分支名称，如果已经存在，则检出本地分支
          git reset --hard source_repo/$branch
          git push origin $branch --force
        done
